#pragma once
#include <string.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <netinet/tcp.h>
#include <netinet/in.h>
#include <linux/socket.h>
#include <arpa/inet.h>
#include <netdb.h>
#include <thread>
#include <time.h>
